---
abstract: 'Add words for spell checking POD'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Wordlist-hanekomu
provides:
  Pod::Wordlist::hanekomu:
    file: lib/Pod/Wordlist/hanekomu.pm
    version: 1.110090
requires:
  Test::Spelling: 0
  perl: 5.008
  utf8: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Wordlist-hanekomu
  homepage: http://search.cpan.org/dist/Pod-Wordlist-hanekomu/
  repository: git://github.com/hanekomu/Pod-Wordlist-hanekomu.git
version: 1.110090
