---
abstract: 'Add words for spell checking POD'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Wordlist-hanekomu
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Pod::Wordlist: 0
  Test::Spelling: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Wordlist-hanekomu
  homepage: http://search.cpan.org/dist/Pod-Wordlist-hanekomu/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/pod-wordlist-hanekomu.git
version: 0.02
