---
abstract: 'Add words for spell checking POD (DEPRECATED)'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Carp: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Wordlist-hanekomu
provides:
  Pod::Wordlist::hanekomu:
    file: lib/Pod/Wordlist/hanekomu.pm
    version: 1.132680
requires:
  Test::Spelling: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Wordlist-hanekomu
  homepage: https://metacpan.org/module/Pod::Wordlist::hanekomu/
  repository: git://github.com/dagolden/Pod-Wordlist-hanekomu.git
version: 1.132680
